const ActionTypes = {
  ADD_BUDGET_CATEGORY: "ADD_BUDGET_CATEGORY",
  REMOVE_BUDGET_CATEGORY: "ADD_BUDGET_CATEGORY",
  ADD_SPEND: "ADD_SPEND",
  REMOVE_SPENDING: "REMOVE_SPENDING",
  ADD_MONTHLY_INCOME: "ADD_MONTHLY_INCOME",
  VIEW_HISTORY: "VIEW_HISTORY",
  UPDATE_SAVING_AMOUNT: "UPDATE_SAVING_AMOUNT",
  UPDATE_BUDGET: "UPDATE_BUDGET",
  RESET_BUDGET: "RESET_BUDGET",
};

export default ActionTypes;
